### PR TITLE
FEATURE: Swagger option on NavBar

### LINKED ISSUE #14: FEATURE: Swagger option on navbar
# User Story

* As a developer
* I can easily turn on the swagger option on the app navbar for any deployment through defining an environment variable `SHOW_SWAGGER_UI_LINK`
* so that it is easy to access swagger when I need it, but I can easily turn it off when I don't.

### Discussion

There is already code in the AppNavbar.js file that checks the value returned by /api/systemInfo for turning the Swagger link on and off.  But, at the moment, the resource file isn't set up to pull that value from an environment variable.

This PR shows what changes are needed to make this work:

https://github.com/ucsb-cs156/proj-courses/pull/93

Your job is just to make similar changes in this repo.

You could also make a similar issue that allows users to turn on/off the H2 console via a variable called `H2_CONSOLE_ENABLED`.  But it would be smart to do that in a separate PR so you get more points!

### Acceptance Criteria

As a developer
- [ ] When the config variable on dokku SHOW_SWAGGER_UI_LINK is set to true, the swagger link shows up
- [ ] When the config variable on dokku SHOW_SWAGGER_UI_LINK is set to false, the swagger link does NOT  show up.

### PR DESCRIPTION
**Pull request by ericpretzel**
Closes #14.

In this PR I implemented the option for developers to enable/disable the swagger ui link in the nav bar. This can be useful to reduce clutter if they are trying to test or demo a (generally frontend) change that does not involve swagger at all. It is set to `true` by default in dev environment and set to `false` by default in prod environment.

With `SHOW_SWAGGER_UI_LINK=true` in the .env or dokku config file, the Swagger UI link appears in the top nav bar:
image

With `SHOW_SWAGGER_UI_LINK=false` in the .env or dokku config file, the link no longer shows up:
image

### CODE REVIEW

**Review by coder626 — DISMISSED** [review]
Looks good on my end

**Review by pconrad — CHANGES_REQUESTED** [review]
You absolutely cannot remove this line:
```
server.port=${PORT:8080}
```

If you do, deployment on platforms such as Heroku and dokku is likely to break.

Please restore it ... and please be careful when making changes to only change what you *must* change for the PR.

**Review by pconrad — DISMISSED** [review]
LGTM.. sorry missed that the removed `server.port=${PORT:8080}` is already in the file so that last one is a duplicate.

**Review by tim-choi — APPROVED** [review]
LGTM!

**Pull request merged**
