### PR TITLE
FEATURE: Added Delete Button to PersonalSchedules page (pt.1)

### LINKED ISSUE #22: FEATURE-SPLIT: Delete Courses From Schedule pt.1
Under Issue #1

### Acceptance Criteria

- [x] The table shown here will have a column with delete buttons
        image

### PR DESCRIPTION
**Pull request by tim-choi**
Before, there was no way to delete a course form your schedule from the personal schedules page. You could only delete a course form the courses page, which was not optimal.

In this PR, I add a column with a delete button for each course under each personal schedule. 

Dokku link: https://proj-courses-timchoi-dev.dokku-03.cs.ucsb.edu/

Screenshot 2024-05-26 at 9 02 03 PM

Closes #22

### CODE REVIEW

**Review by whuang602 — CHANGES_REQUESTED** [review]
Can we get a dokku deployment for this PR? Note that whenever this gets merged, the staff can move forward with reviewing and merging #44

**Comment by tim-choi** [comment]
> Can we get a dokku deployment for this PR? Note that whenever this gets merged, the staff can move forward with reviewing and merging #44

https://proj-courses-timchoi-dev.dokku-03.cs.ucsb.edu/ Yes!

**Review by coder626 — DISMISSED** [review]
Looks good, I tested on my end and the button appears

**Comment by pconrad** [comment]
> > Can we get a dokku deployment for this PR? Note that whenever this gets merged, the staff can move forward with reviewing and merging #44
> 
> https://proj-courses-timchoi-dev.dokku-03.cs.ucsb.edu/ Yes!

Please put these dokku links in the description up top where we can find them.

**Review by whuang602 — CHANGES_REQUESTED** [review]
Code currently seems broken on in deployment. This is the error I see.
Screenshot 2024-05-29 at 5 08 34 PM

**Comment by tim-choi** [comment]
> Code currently seems broken on in deployment. This is the error I see. Screenshot 2024-05-29 at 5 08 34 PM

The PR is just adding the delete button to the table, I have the functionality in a different PR

**Pull request closed without merging**
